### ISSUE TITLE
Leads stay connected over millions of blocks

### ISSUE THREAD

**Issue by MCTGE** [DevCyntrix/entity-traveller#1]
**Issue:**
If you teleport to a World Guard region that has the flag Mob-Spawning: Deny, the mobs do not come with the player however, as soon as you leave the protected area the lead shows up again going off way into the distance with seemingly no limit to its distance. This is a problem when players use the /spawn command in my circumstance.

Sometimes if you teleport again after leaving the protected area the mobs will show up, and then sometimes they do not.  When they do not the lead vanishes however it is still active and can be placed on a fence post.

**Expected Functionality:**
When teleporting to a region where mobs can not exist the lead should be broken. 

**Possible Solutions:**
1. Return the functionality of leads breaking at XX distance.

2. Tap into the World Guard API and have leads break when entering protected areas.  This wouldn't be ideal since there are dozens of other plugins that can block mob spawning. 

3. Add a check to see if the teleportation was successful by checking if the mob moved over XX amount of blocks.  If the check fails the lead breaks. 

4. The lead breaks after all teleportations are complete

5. Add a blacklist to the configs that will break the leads when using certain commands. It would need to accept spaces since you might need to block a specific warp such as /warp Arena.

![Screenshot 2022-04-17 102426](https://user-images.githubusercontent.com/93126894/163721211-c0fa48d5-30da-4161-9721-75d6ec8b9e4c.png)

**Comment by DevCyntrix** [comment]
Thank you for the issue. I will fix it soon. 👍
